# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_service(object):
    def setupUi(self, service):
        service.setObjectName("service")
        service.resize(1063, 600)
        self.centralwidget = QtWidgets.QWidget(service)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 271, 151))
        self.widget.setStyleSheet("background-color: rgb(92, 92, 92);")
        self.widget.setObjectName("widget")
        self.profilePic = QtWidgets.QWidget(self.widget)
        self.profilePic.setGeometry(QtCore.QRect(10, 10, 101, 121))
        self.profilePic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.profilePic.setObjectName("profilePic")
        self.ID_lable = QtWidgets.QLabel(self.widget)
        self.ID_lable.setGeometry(QtCore.QRect(130, 20, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ID_lable.setFont(font)
        self.ID_lable.setObjectName("ID_lable")
        self.NAME_lable = QtWidgets.QLabel(self.widget)
        self.NAME_lable.setGeometry(QtCore.QRect(130, 60, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NAME_lable.setFont(font)
        self.NAME_lable.setObjectName("NAME_lable")
        self.RANK_label = QtWidgets.QLabel(self.widget)
        self.RANK_label.setGeometry(QtCore.QRect(130, 100, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RANK_label.setFont(font)
        self.RANK_label.setObjectName("RANK_label")
        self.logout = QtWidgets.QPushButton(self.widget)
        self.logout.setGeometry(QtCore.QRect(120, 129, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.logout.setObjectName("logout")
        self.menu = QtWidgets.QComboBox(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(20, 190, 271, 25))
        self.menu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(97, 97, 97);")
        self.menu.setObjectName("menu")
        self.menu.addItem("")
        self.menu.addItem("")
        self.search = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(20, 230, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search.sizePolicy().hasHeightForWidth())
        self.search.setSizePolicy(sizePolicy)
        self.search.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.search.setObjectName("search")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(320, 20, 731, 531))
        self.widget_3.setStyleSheet("background-color: rgb(92, 92, 92);")
        self.widget_3.setObjectName("widget_3")
        self.thumnail1 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail1.setGeometry(QtCore.QRect(20, 20, 121, 131))
        self.thumnail1.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail1.setText("")
        self.thumnail1.setObjectName("thumnail1")
        self.thumnail2 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail2.setGeometry(QtCore.QRect(210, 20, 121, 131))
        self.thumnail2.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail2.setText("")
        self.thumnail2.setObjectName("thumnail2")
        self.thumnail3 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail3.setGeometry(QtCore.QRect(400, 20, 121, 131))
        self.thumnail3.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail3.setText("")
        self.thumnail3.setObjectName("thumnail3")
        self.thumnail4 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail4.setGeometry(QtCore.QRect(590, 20, 121, 131))
        self.thumnail4.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail4.setText("")
        self.thumnail4.setObjectName("thumnail4")
        self.thumnail5 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail5.setGeometry(QtCore.QRect(20, 190, 121, 131))
        self.thumnail5.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail5.setText("")
        self.thumnail5.setObjectName("thumnail5")
        self.thumnail6 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail6.setGeometry(QtCore.QRect(210, 190, 121, 131))
        self.thumnail6.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail6.setText("")
        self.thumnail6.setObjectName("thumnail6")
        self.thumnail7 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail7.setGeometry(QtCore.QRect(400, 190, 121, 131))
        self.thumnail7.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail7.setText("")
        self.thumnail7.setObjectName("thumnail7")
        self.thumnail8 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail8.setGeometry(QtCore.QRect(590, 190, 121, 131))
        self.thumnail8.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail8.setText("")
        self.thumnail8.setObjectName("thumnail8")
        self.thumnail9 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail9.setGeometry(QtCore.QRect(20, 360, 121, 131))
        self.thumnail9.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail9.setText("")
        self.thumnail9.setObjectName("thumnail9")
        self.thumnail10 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail10.setGeometry(QtCore.QRect(210, 360, 121, 131))
        self.thumnail10.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail10.setText("")
        self.thumnail10.setObjectName("thumnail10")
        self.thumnail11 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail11.setGeometry(QtCore.QRect(400, 360, 121, 131))
        self.thumnail11.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail11.setText("")
        self.thumnail11.setObjectName("thumnail11")
        self.thumnail12 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail12.setGeometry(QtCore.QRect(590, 360, 121, 131))
        self.thumnail12.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail12.setText("")
        self.thumnail12.setObjectName("thumnail12")
        self.t_label1 = QtWidgets.QLabel(self.widget_3)
        self.t_label1.setGeometry(QtCore.QRect(20, 150, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label1.setFont(font)
        self.t_label1.setText("")
        self.t_label1.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label1.setObjectName("t_label1")
        self.t_label2 = QtWidgets.QLabel(self.widget_3)
        self.t_label2.setGeometry(QtCore.QRect(210, 150, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label2.setFont(font)
        self.t_label2.setText("")
        self.t_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label2.setObjectName("t_label2")
        self.t_label3 = QtWidgets.QLabel(self.widget_3)
        self.t_label3.setGeometry(QtCore.QRect(400, 150, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label3.setFont(font)
        self.t_label3.setText("")
        self.t_label3.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label3.setObjectName("t_label3")
        self.t_label4 = QtWidgets.QLabel(self.widget_3)
        self.t_label4.setGeometry(QtCore.QRect(590, 150, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label4.setFont(font)
        self.t_label4.setText("")
        self.t_label4.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label4.setObjectName("t_label4")
        self.t_label5 = QtWidgets.QLabel(self.widget_3)
        self.t_label5.setGeometry(QtCore.QRect(20, 320, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label5.setFont(font)
        self.t_label5.setText("")
        self.t_label5.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label5.setObjectName("t_label5")
        self.t_label6 = QtWidgets.QLabel(self.widget_3)
        self.t_label6.setGeometry(QtCore.QRect(210, 320, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label6.setFont(font)
        self.t_label6.setText("")
        self.t_label6.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label6.setObjectName("t_label6")
        self.t_label7 = QtWidgets.QLabel(self.widget_3)
        self.t_label7.setGeometry(QtCore.QRect(400, 320, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label7.setFont(font)
        self.t_label7.setText("")
        self.t_label7.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label7.setObjectName("t_label7")
        self.t_label8 = QtWidgets.QLabel(self.widget_3)
        self.t_label8.setGeometry(QtCore.QRect(590, 320, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label8.setFont(font)
        self.t_label8.setText("")
        self.t_label8.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label8.setObjectName("t_label8")
        self.t_label9 = QtWidgets.QLabel(self.widget_3)
        self.t_label9.setGeometry(QtCore.QRect(20, 490, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label9.setFont(font)
        self.t_label9.setText("")
        self.t_label9.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label9.setObjectName("t_label9")
        self.t_label10 = QtWidgets.QLabel(self.widget_3)
        self.t_label10.setGeometry(QtCore.QRect(210, 490, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label10.setFont(font)
        self.t_label10.setText("")
        self.t_label10.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label10.setObjectName("t_label10")
        self.t_label11 = QtWidgets.QLabel(self.widget_3)
        self.t_label11.setGeometry(QtCore.QRect(400, 490, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label11.setFont(font)
        self.t_label11.setText("")
        self.t_label11.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label11.setObjectName("t_label11")
        self.t_label12 = QtWidgets.QLabel(self.widget_3)
        self.t_label12.setGeometry(QtCore.QRect(590, 490, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_label12.setFont(font)
        self.t_label12.setText("")
        self.t_label12.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label12.setObjectName("t_label12")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(260, 230, 31, 31))
        self.searchButton.setText("")
        self.searchButton.setObjectName("searchButton")
        self.searchResult = QtWidgets.QListWidget(self.centralwidget)
        self.searchResult.setGeometry(QtCore.QRect(20, 270, 271, 281))
        self.searchResult.setObjectName("searchResult")
        item = QtWidgets.QListWidgetItem()
        self.searchResult.addItem(item)
        service.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(service)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 23))
        self.menubar.setObjectName("menubar")
        service.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(service)
        self.statusbar.setObjectName("statusbar")
        service.setStatusBar(self.statusbar)

        self.retranslateUi(service)
        QtCore.QMetaObject.connectSlotsByName(service)

    def retranslateUi(self, service):
        _translate = QtCore.QCoreApplication.translate
        service.setWindowTitle(_translate("service", "service"))
        self.ID_lable.setText(_translate("service", "ID : "))
        self.NAME_lable.setText(_translate("service", "NAME : "))
        self.RANK_label.setText(_translate("service", "RANK : "))
        self.logout.setText(_translate("service", "로그아웃"))
        self.menu.setItemText(0, _translate("service", "구독목록"))
        self.menu.setItemText(1, _translate("service", "최근시청목록"))
        self.search.setPlainText(_translate("service", "검색"))
        __sortingEnabled = self.searchResult.isSortingEnabled()
        self.searchResult.setSortingEnabled(False)
        item = self.searchResult.item(0)
        item.setText(_translate("service", "검색 결과"))
        self.searchResult.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    service = QtWidgets.QMainWindow()
    ui = Ui_service()
    ui.setupUi(service)
    service.show()
    sys.exit(app.exec_())

