# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_service(object):
    def setupUi(self, service):
        service.setObjectName("service")
        service.resize(1048, 600)
        self.centralwidget = QtWidgets.QWidget(service)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 271, 151))
        self.widget.setStyleSheet("background-color: rgb(92, 92, 92);")
        self.widget.setObjectName("widget")
        self.profilePic = QtWidgets.QWidget(self.widget)
        self.profilePic.setGeometry(QtCore.QRect(10, 10, 101, 121))
        self.profilePic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.profilePic.setObjectName("profilePic")
        self.ID_lable = QtWidgets.QLabel(self.widget)
        self.ID_lable.setGeometry(QtCore.QRect(130, 20, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ID_lable.setFont(font)
        self.ID_lable.setObjectName("ID_lable")
        self.NAME_lable = QtWidgets.QLabel(self.widget)
        self.NAME_lable.setGeometry(QtCore.QRect(130, 60, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NAME_lable.setFont(font)
        self.NAME_lable.setObjectName("NAME_lable")
        self.RANK_label = QtWidgets.QLabel(self.widget)
        self.RANK_label.setGeometry(QtCore.QRect(130, 100, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RANK_label.setFont(font)
        self.RANK_label.setObjectName("RANK_label")
        self.logout = QtWidgets.QPushButton(self.widget)
        self.logout.setGeometry(QtCore.QRect(120, 129, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.logout.setObjectName("logout")
        self.menu = QtWidgets.QComboBox(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(20, 190, 271, 25))
        self.menu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(97, 97, 97);")
        self.menu.setObjectName("menu")
        self.menu.addItem("")
        self.menu.addItem("")
        self.search = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(20, 230, 271, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search.sizePolicy().hasHeightForWidth())
        self.search.setSizePolicy(sizePolicy)
        self.search.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.search.setObjectName("search")
        self.searchResult = QtWidgets.QTextBrowser(self.centralwidget)
        self.searchResult.setGeometry(QtCore.QRect(20, 270, 271, 281))
        self.searchResult.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchResult.setObjectName("searchResult")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(320, 20, 731, 531))
        self.widget_3.setStyleSheet("background-color: rgb(92, 92, 92);")
        self.widget_3.setObjectName("widget_3")
        self.thumnail1 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail1.setGeometry(QtCore.QRect(20, 20, 121, 151))
        self.thumnail1.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail1.setText("")
        self.thumnail1.setObjectName("thumnail1")
        self.thumnail2 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail2.setGeometry(QtCore.QRect(210, 20, 121, 151))
        self.thumnail2.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail2.setText("")
        self.thumnail2.setObjectName("thumnail2")
        self.thumnail3 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail3.setGeometry(QtCore.QRect(400, 20, 121, 151))
        self.thumnail3.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail3.setText("")
        self.thumnail3.setObjectName("thumnail3")
        self.thumnail4 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail4.setGeometry(QtCore.QRect(590, 20, 121, 151))
        self.thumnail4.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail4.setText("")
        self.thumnail4.setObjectName("thumnail4")
        self.thumnail5 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail5.setGeometry(QtCore.QRect(20, 190, 121, 151))
        self.thumnail5.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail5.setText("")
        self.thumnail5.setObjectName("thumnail5")
        self.thumnail6 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail6.setGeometry(QtCore.QRect(210, 190, 121, 151))
        self.thumnail6.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail6.setText("")
        self.thumnail6.setObjectName("thumnail6")
        self.thumnail7 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail7.setGeometry(QtCore.QRect(400, 190, 121, 151))
        self.thumnail7.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail7.setText("")
        self.thumnail7.setObjectName("thumnail7")
        self.thumnail8 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail8.setGeometry(QtCore.QRect(590, 190, 121, 151))
        self.thumnail8.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail8.setText("")
        self.thumnail8.setObjectName("thumnail8")
        self.thumnail9 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail9.setGeometry(QtCore.QRect(20, 360, 121, 151))
        self.thumnail9.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail9.setText("")
        self.thumnail9.setObjectName("thumnail9")
        self.thumnail10 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail10.setGeometry(QtCore.QRect(210, 360, 121, 151))
        self.thumnail10.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail10.setText("")
        self.thumnail10.setObjectName("thumnail10")
        self.thumnail11 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail11.setGeometry(QtCore.QRect(400, 360, 121, 151))
        self.thumnail11.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail11.setText("")
        self.thumnail11.setObjectName("thumnail11")
        self.thumnail12 = QtWidgets.QPushButton(self.widget_3)
        self.thumnail12.setGeometry(QtCore.QRect(590, 360, 121, 151))
        self.thumnail12.setStyleSheet("color: rgb(156, 156, 156);")
        self.thumnail12.setText("")
        self.thumnail12.setObjectName("thumnail12")
        service.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(service)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 23))
        self.menubar.setObjectName("menubar")
        service.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(service)
        self.statusbar.setObjectName("statusbar")
        service.setStatusBar(self.statusbar)

        self.retranslateUi(service)
        QtCore.QMetaObject.connectSlotsByName(service)

    def retranslateUi(self, service):
        _translate = QtCore.QCoreApplication.translate
        service.setWindowTitle(_translate("service", "service"))
        self.ID_lable.setText(_translate("service", "ID : "))
        self.NAME_lable.setText(_translate("service", "NAME : "))
        self.RANK_label.setText(_translate("service", "RANK : "))
        self.logout.setText(_translate("service", "로그아웃"))
        self.menu.setItemText(0, _translate("service", "구독목록"))
        self.menu.setItemText(1, _translate("service", "최근시청목록"))
        self.search.setPlainText(_translate("service", "검색"))
        self.searchResult.setHtml(_translate("service", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">검색결과</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    service = QtWidgets.QMainWindow()
    ui = Ui_service()
    ui.setupUi(service)
    service.show()
    sys.exit(app.exec_())

